---
- name: pkg - Install package
  apt:
    deb: "http://nexus.genscript.com/repository/it/ppa.genscript.com/monit/5.26.0-1~ppa-genscript-ubuntu1/monit_5.26.0-1~ppa-genscript-ubuntu1_amd64.deb"
    state: present
